### ISSUE TITLE
Disable caching in the dist docker image

### ISSUE THREAD

**Issue by bashlk** [international-labour-organization/ilo_base_theme#10]
Currently the dist docker image has caching enabled so changes to the design system assets are not immediately reflected on the theme site. We should disable caching so that the site always reflects the state of the assets on the disk.

(Context: https://github.com/international-labour-organization/designsystem/pull/984)

**Comment by ademarco** [comment]
I'll disable caching by default since we use the images for testing and dev purposes only.
