### ISSUE TITLE
Add boolval filter to support ILO Design Kit >=1.1.0

### ISSUE THREAD

**Issue by ademarco** [international-labour-organization/ilo_base_theme#13]
In the next minor version of the ILO Design System (most likely 1.1.0) Twig components need a boolval filter to function correctly. The scope of this ticket is to provide such a filter.

This depends on https://github.com/international-labour-organization/designsystem/issues/965 being merged and releases.

**Comment by ademarco** [comment]
@justintemps this is now ready for review, if merged then I'll release 0.2.0.

**Comment by justintemps** [comment]
Hey @ademarco, yes 1.1.0 is now released.
