### ISSUE TITLE
Twig: Youtube video player is not rendering in standalone url.

### ISSUE THREAD

**Issue by Shashika6** [international-labour-organization/ilo_base_theme#20]
The youtube video player is not rendering as expected for the stand alone URL which is used for the tests. 

* It is working as expected in the `/patterns#youtube_video` but not in the standalone URL.

Screenshot : 

![Screenshot 2024-06-26 at 01 42 36](https://github.com/international-labour-organization/ilo_base_theme/assets/32934169/5b1b8d0b-966d-4c53-811f-28ad67ecb70d)

**Comment by ademarco** [comment]
This seems to be working in the latest version of the DS. Closing.
