### ISSUE TITLE
Integrate breadcrumb with Design System

### ISSUE THREAD

**Issue by ademarco** [international-labour-organization/ilo_base_theme#40]
Integrate the breadcrumb component from the ILO Design System with the existing Drupal breadcrumb functionality. Ensure that the design and structure align with the ILO guidelines while maintaining the dynamic functionality of Drupal's breadcrumb system.

**Comment by justintemps** [comment]
Hey @ademarco careful to note also that the Hero also implements the Breadcrumb as a sub-component
